# Generated by Django 5.1.1 on 2024-09-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
